### ISSUE TITLE
... doesn't work?

### ISSUE THREAD

**Issue by haroldallen** [doupkg/lapcord#7]
Installed the plugin into Lapce and installed the server npm package globally.
Have tried restarting Lapce. Nothing happens.

Is there some command I have to run, e.g. npx lapcord-server? If so, you should really add it to the installation instructions.

**Comment by yehorovye** [comment]
Hello and thanks for opening an issue, can you provide me which OS are you using? did you install it via NPM or Yarn? You also should have installed the correspondant binaries of your package manager.

**Comment by hyduez** [comment]
> Installed the plugin into Lapce and installed the server npm package globally. Have tried restarting Lapce. Nothing happens.
> 
> Is there some command I have to run, e.g. npx lapcord-server? If so, you should really add it to the installation instructions.

Thank you for the time you have taken since you decided to test Lapcord and record the issues you were getting. The bug is fixed, the fault lies with me. I didn't specify in [package.json](https://github.com/doupkg/lapcord-server/blob/master/package.json) the files that should be uploaded, so NPM took .gitignore as an example and it ignored the dist directory! Now [version 1.1.1](https://github.com/doupkg/lapcord-server/releases/tag/v1.1.1) is available. Now the binaries exist.

Sorry.

**Comment by haroldallen** [comment]
Thank you!
